### ISSUE TITLE
Handle `AccessDenied` exceptions when fetching config of S3 Buckets

### ISSUE THREAD

**Issue by PChol22** [sls-mentor/sls-mentor#113]
When fetching Buckets that have restrictive access policies, sls-mentor encounters a `AccessDenied` exception that is not handled.

I see in the code that other exceptions like `PermanentRedirect` are handled in the case of S3 buckets, it should be possible to do the same.

I encountered the problem while using the `UseIntelligentTiering` rule, but it may be present for other Rules / Services too

**Comment by ayhan-inawisdom** [comment]
I have hit the same issue. Currently, if there is an S3 bucket with restrictive access, the sls-mentor falls over and cannot produce the results. Is there any way you can select specific rules or even skip errors?

**Comment by JamesKyburz** [comment]
Duplicate of #163
