### ISSUE TITLE
New rule : CloudFront distributions should be associated with a SSL certificate

### ISSUE THREAD

**Issue by PChol22** [sls-mentor/sls-mentor#155]
CloudFront distributions should be associated with a SSL certificate

There are 2 types of SSL certificates that can be associated :
- ACM
- IAM

Check the presence of one of them (NOT BOTH (its not possible)) for the check to be OK

Sources :
https://aws.amazon.com/premiumsupport/knowledge-center/install-ssl-cloudfront/

**Comment by jeanneleparc** [comment]
I am working on adding this rule
