### ISSUE TITLE
S3 encryption rule should follow redirects

### ISSUE THREAD

**Issue by ealain** [sls-mentor/sls-mentor#163]
# Actual behavior

When a bucket ends up in `eu-west-3` and the profile is configured on `eu-west-1`, `fetchS3BucketEncryptionConfigurationByArn` will catch the `PermanentRedirect` and return `undefined`.

# Expected behavior

1. [prefered] follow the redirection
2. filter out buckets outside the configured region before analysis, but this makes less sense as buckets are global resources

**Comment by JamesKyburz** [comment]
https://github.com/sls-mentor/sls-mentor/pull/207 addresses this by filtering the buckets for the given reason. I chose this option as s3 buckets are a regional resource.
