### ISSUE TITLE
Tests fail locally

### ISSUE THREAD

**Issue by adelego** [sls-mentor/sls-mentor#213]
I'm trying to run tests locally on master branch and they fail.

I have run:

```[bash]
pnpm install
cd apps/test
pnpm run deploy ## this has deployed a stack to my default AWS account
pnpm test
```

I see warning error: `Unable to fetch AWS resources, check that your default profile is correctly set and has the needed rights or that you have correctly set environment variables`

<img width="741" alt="image" src="https://github.com/sls-mentor/sls-mentor/assets/28386375/682f5889-53cd-40dd-964f-a8f1b820a35d">
<img width="614" alt="image" src="https://github.com/sls-mentor/sls-mentor/assets/28386375/18c58dc0-643b-4260-9805-e99116981a41">

However my default account is set.

**Comment by PChol22** [comment]
should be fixed now that we have refactored the repo !
