### ISSUE TITLE
Socket connection timeout error

### ISSUE THREAD

**Issue by mnapoli** [sls-mentor/sls-mentor#214]
Hey, I'm getting a "Socket connection timeout" mid-analysis. The trace is not really helpful unfortunately :/ Maybe the AWS SDK times out for some reason? (my internet connection is supposed to be good FYI)

```
Welcome to sls-mentor 🛡️.

Let's start by selecting the level of difficulty you want me to check your code against.


👊  Let's get these resources REALLY clean..



⠴ Processing rules 12/19...node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error [ERR_SOCKET_CONNECTION_TIMEOUT]: Socket connection timeout
    at new NodeError (node:internal/errors:399:5)
    at internalConnectMultiple (node:net:1099:20)
    at Timeout.internalConnectMultipleTimeout (node:net:1638:3)
    at listOnTimeout (node:internal/timers:575:11)
    at process.processTimers (node:internal/timers:514:7) {
  code: 'ERR_SOCKET_CONNECTION_TIMEOUT',
  '$metadata': { attempts: 1, totalRetryDelay: 0 }
}

Node.js v20.2.0
```

**Comment by PChol22** [comment]
I'm trying to investigate this issue, does it happen every time or is it some random behavior ?

**Comment by mnapoli** [comment]
Hey! The client project is done so I can't reproduce, but I think it was happening every time. We can close this if you want?

**Comment by PChol22** [comment]
Ok sorry for my poor responsiveness, do not hesitate to ping me if you ever encounter the problem again. I will try to be a bit more prompt 🙃
