### ISSUE TITLE
Support SSO authentication

### ISSUE THREAD

**Issue by matthieujacq** [sls-mentor/sls-mentor#231]
Currently, sls-mentor does not work well with SSO.

## Reproduce

```sh
assume
# select the profile
pnpm run dev
```
Error message :
```
⠇ Connecting to AWS...CredentialsProviderError: The SSO session associated with this profile has expired. To refresh this SSO session run aws sso login with the corresponding profile.
```

I also tried  (but did not work either) :
- `aws sso login --profile <PROFILE>`
-  `assume -c <PROFILE>`

(At some point I had a different error message : `CredentialsProviderError: Could not load credentials from any providers`)

**Comment by PChol22** [comment]
I created a new issue (#247) with more precise investigation information and started to think about strategies to fix the problem. I'm closing this one.
