### ISSUE TITLE
Running `npm run dev` breaks my terminal in case of error

### ISSUE THREAD

**Issue by ealain** [sls-mentor/sls-mentor#90]
## Actual behavior

As mentioned in the CONTRIBUTING file, run:
```
npm run dev -- -p <profile>
```

This produces the following output on my terminal:

![image](https://user-images.githubusercontent.com/19293102/206726531-c62bfce5-6fa8-4796-9338-073394d17c64.png)

Then I do not see my cursor anymore.

## Expected behavior

Returns a clean error and leave the terminal in a normal state.

**Comment by QuentinNativel** [comment]
Fixes by #144
